context:
  version: VERSION_PLACEHOLDER

package:
  name: r-pecotmr
  version: ${{ version }}

source:
  path: pecotmr-${{ version }}.tar.gz
  sha256: SHA256SUM_PLACEHOLDER

build:
  number: BUILD_PLACEHOLDER
  dynamic_linking:
    rpaths:
      - lib/R/lib/
      - lib/
  script: R CMD INSTALL --build .

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - ${{ compiler('cxx') }}
  host:
    - bioconductor-biocparallel
    - bioconductor-biostrings
    - bioconductor-genomicranges
    - bioconductor-iranges
    - bioconductor-qvalue
    - bioconductor-s4vectors
    - bioconductor-snprelate
    - bioconductor-snpstats
    - bioconductor-mungesumstats
    - bioconductor-rsamtools
    - bioconductor-rtracklayer
    - bioconductor-summarizedexperiment
    - r-arrow
    - r-aspu
    - r-base
    - r-bglr
    - r-bigsnpr
    - r-coda
    - r-coloc
    - r-colocboost
    - r-cpp11
    - r-cpp11armadillo
    - r-decor
    - r-dplyr
    - r-flashier
    - r-fsusier
    - r-gbj
    - r-glmnet
    - r-harmonicmeanp
    - r-igraph
    - r-l0learn
    - r-magrittr
    - r-mashr
    - r-matrix
    - r-matrixstats
    - r-mr.ash.alpha
    - r-mr.mashr
    - r-mvsusier
    - r-ncvreg
    - r-nnls
    - r-pgenlibr
    - r-plinkqc
    - r-poolr
    - r-purrr
    - r-qgg
    - r-quadprog
    - r-rcppdpr
    - r-readr
    - r-rfast
    - r-rlang
    - r-stringr
    - r-susier
    - r-tibble
    - r-tictoc
    - r-tidyr
    - r-vctrs
    - r-vroom
    - r-xgboost
  run:
    - bioconductor-biocparallel
    - bioconductor-genomicranges
    - bioconductor-iranges
    - bioconductor-qvalue
    - bioconductor-s4vectors
    - bioconductor-snprelate
    - bioconductor-snpstats
    - bioconductor-mungesumstats
    - bioconductor-rsamtools
    - bioconductor-rtracklayer
    - bioconductor-summarizedexperiment
    - r-arrow
    - r-aspu
    - r-base
    - r-bglr
    - r-bigsnpr
    - r-coda
    - r-coloc
    - r-colocboost
    - r-cpp11
    - r-cpp11armadillo
    - r-decor
    - r-dplyr
    - r-flashier
    - r-fsusier
    - r-gbj
    - r-glmnet
    - r-harmonicmeanp
    - r-igraph
    - r-l0learn
    - r-magrittr
    - r-mashr
    - r-matrix
    - r-matrixstats
    - r-mr.ash.alpha
    - r-mr.mashr
    - r-mvsusier
    - r-ncvreg
    - r-nnls
    - r-pgenlibr
    - r-plinkqc
    - r-poolr
    - r-purrr
    - r-qgg
    - r-quadprog
    - r-rcppdpr
    - r-readr
    - r-rfast
    - r-rlang
    - r-stringr
    - r-susier
    - r-tibble
    - r-tictoc
    - r-tidyr
    - r-vctrs
    - r-vroom
    - r-xgboost

tests:
  - script:
      - R -e "library('pecotmr')"

about:
  license: MIT
  license_file: LICENSE
  summary: pecotmr implements pair-wise enrichment, colocalization, TWAS and Mendelian Randomization to integrate QTL and GWAS analysis based on a fine-mapped single effects model.
  homepage: https://github.com/StatFunGen/pecotmr

extra:
  recipe-maintainers:
    - danielnachun
