// Generated by cpp11: do not edit by hand
// clang-format off


#include "cpp11/declarations.hpp"
#include <R_ext/Visibility.h>

// dentist_iterative_impute.cpp
cpp11::writable::list dentist_iterative_impute(const doubles_matrix<>& LD_mat_r, int nSample, const doubles& zScore_r, double pValueThreshold, double propSVD, bool gcControl, int nIter, double gPvalueThreshold, int ncpus, bool correct_chen_et_al_bug, bool verbose);
extern "C" SEXP _pecotmr_dentist_iterative_impute(SEXP LD_mat_r, SEXP nSample, SEXP zScore_r, SEXP pValueThreshold, SEXP propSVD, SEXP gcControl, SEXP nIter, SEXP gPvalueThreshold, SEXP ncpus, SEXP correct_chen_et_al_bug, SEXP verbose) {
  BEGIN_CPP11
    return cpp11::as_sexp(dentist_iterative_impute(cpp11::as_cpp<cpp11::decay_t<const doubles_matrix<>&>>(LD_mat_r), cpp11::as_cpp<cpp11::decay_t<int>>(nSample), cpp11::as_cpp<cpp11::decay_t<const doubles&>>(zScore_r), cpp11::as_cpp<cpp11::decay_t<double>>(pValueThreshold), cpp11::as_cpp<cpp11::decay_t<double>>(propSVD), cpp11::as_cpp<cpp11::decay_t<bool>>(gcControl), cpp11::as_cpp<cpp11::decay_t<int>>(nIter), cpp11::as_cpp<cpp11::decay_t<double>>(gPvalueThreshold), cpp11::as_cpp<cpp11::decay_t<int>>(ncpus), cpp11::as_cpp<cpp11::decay_t<bool>>(correct_chen_et_al_bug), cpp11::as_cpp<cpp11::decay_t<bool>>(verbose)));
  END_CPP11
}
// lassosum_rss.cpp
cpp11::writable::list lassosum_rss_rcpp(const doubles& z_r, const list& LD, const doubles& lambda_r, double thr, int maxiter);
extern "C" SEXP _pecotmr_lassosum_rss_rcpp(SEXP z_r, SEXP LD, SEXP lambda_r, SEXP thr, SEXP maxiter) {
  BEGIN_CPP11
    return cpp11::as_sexp(lassosum_rss_rcpp(cpp11::as_cpp<cpp11::decay_t<const doubles&>>(z_r), cpp11::as_cpp<cpp11::decay_t<const list&>>(LD), cpp11::as_cpp<cpp11::decay_t<const doubles&>>(lambda_r), cpp11::as_cpp<cpp11::decay_t<double>>(thr), cpp11::as_cpp<cpp11::decay_t<int>>(maxiter)));
  END_CPP11
}
// prscs_mcmc.cpp
cpp11::writable::list prs_cs_rcpp(double a, double b, sexp phi, doubles bhat, sexp maf, int n, list ld_blk, int n_iter, int n_burnin, int thin, bool verbose, sexp seed);
extern "C" SEXP _pecotmr_prs_cs_rcpp(SEXP a, SEXP b, SEXP phi, SEXP bhat, SEXP maf, SEXP n, SEXP ld_blk, SEXP n_iter, SEXP n_burnin, SEXP thin, SEXP verbose, SEXP seed) {
  BEGIN_CPP11
    return cpp11::as_sexp(prs_cs_rcpp(cpp11::as_cpp<cpp11::decay_t<double>>(a), cpp11::as_cpp<cpp11::decay_t<double>>(b), cpp11::as_cpp<cpp11::decay_t<sexp>>(phi), cpp11::as_cpp<cpp11::decay_t<doubles>>(bhat), cpp11::as_cpp<cpp11::decay_t<sexp>>(maf), cpp11::as_cpp<cpp11::decay_t<int>>(n), cpp11::as_cpp<cpp11::decay_t<list>>(ld_blk), cpp11::as_cpp<cpp11::decay_t<int>>(n_iter), cpp11::as_cpp<cpp11::decay_t<int>>(n_burnin), cpp11::as_cpp<cpp11::decay_t<int>>(thin), cpp11::as_cpp<cpp11::decay_t<bool>>(verbose), cpp11::as_cpp<cpp11::decay_t<sexp>>(seed)));
  END_CPP11
}
// qtl_enrichment.cpp
cpp11::writable::list qtl_enrichment_rcpp(SEXP r_gwas_pip, SEXP r_qtl_susie_fit, double pi_gwas, double pi_qtl, int ImpN, double shrinkage_lambda, bool double_shrinkage, bool bessel_correction, int num_threads);
extern "C" SEXP _pecotmr_qtl_enrichment_rcpp(SEXP r_gwas_pip, SEXP r_qtl_susie_fit, SEXP pi_gwas, SEXP pi_qtl, SEXP ImpN, SEXP shrinkage_lambda, SEXP double_shrinkage, SEXP bessel_correction, SEXP num_threads) {
  BEGIN_CPP11
    return cpp11::as_sexp(qtl_enrichment_rcpp(cpp11::as_cpp<cpp11::decay_t<SEXP>>(r_gwas_pip), cpp11::as_cpp<cpp11::decay_t<SEXP>>(r_qtl_susie_fit), cpp11::as_cpp<cpp11::decay_t<double>>(pi_gwas), cpp11::as_cpp<cpp11::decay_t<double>>(pi_qtl), cpp11::as_cpp<cpp11::decay_t<int>>(ImpN), cpp11::as_cpp<cpp11::decay_t<double>>(shrinkage_lambda), cpp11::as_cpp<cpp11::decay_t<bool>>(double_shrinkage), cpp11::as_cpp<cpp11::decay_t<bool>>(bessel_correction), cpp11::as_cpp<cpp11::decay_t<int>>(num_threads)));
  END_CPP11
}
// sdpr.cpp
cpp11::writable::list sdpr_rcpp(const doubles& bhat_r, const list& LD, int n, sexp per_variant_sample_size, sexp array, double a, double c, int M, double a0k, double b0k, int iter, int burn, int thin, int n_threads, int opt_llk, bool verbose, sexp seed);
extern "C" SEXP _pecotmr_sdpr_rcpp(SEXP bhat_r, SEXP LD, SEXP n, SEXP per_variant_sample_size, SEXP array, SEXP a, SEXP c, SEXP M, SEXP a0k, SEXP b0k, SEXP iter, SEXP burn, SEXP thin, SEXP n_threads, SEXP opt_llk, SEXP verbose, SEXP seed) {
  BEGIN_CPP11
    return cpp11::as_sexp(sdpr_rcpp(cpp11::as_cpp<cpp11::decay_t<const doubles&>>(bhat_r), cpp11::as_cpp<cpp11::decay_t<const list&>>(LD), cpp11::as_cpp<cpp11::decay_t<int>>(n), cpp11::as_cpp<cpp11::decay_t<sexp>>(per_variant_sample_size), cpp11::as_cpp<cpp11::decay_t<sexp>>(array), cpp11::as_cpp<cpp11::decay_t<double>>(a), cpp11::as_cpp<cpp11::decay_t<double>>(c), cpp11::as_cpp<cpp11::decay_t<int>>(M), cpp11::as_cpp<cpp11::decay_t<double>>(a0k), cpp11::as_cpp<cpp11::decay_t<double>>(b0k), cpp11::as_cpp<cpp11::decay_t<int>>(iter), cpp11::as_cpp<cpp11::decay_t<int>>(burn), cpp11::as_cpp<cpp11::decay_t<int>>(thin), cpp11::as_cpp<cpp11::decay_t<int>>(n_threads), cpp11::as_cpp<cpp11::decay_t<int>>(opt_llk), cpp11::as_cpp<cpp11::decay_t<bool>>(verbose), cpp11::as_cpp<cpp11::decay_t<sexp>>(seed)));
  END_CPP11
}

extern "C" {
static const R_CallMethodDef CallEntries[] = {
    {"_pecotmr_dentist_iterative_impute", (DL_FUNC) &_pecotmr_dentist_iterative_impute, 11},
    {"_pecotmr_lassosum_rss_rcpp",        (DL_FUNC) &_pecotmr_lassosum_rss_rcpp,         5},
    {"_pecotmr_prs_cs_rcpp",              (DL_FUNC) &_pecotmr_prs_cs_rcpp,              12},
    {"_pecotmr_qtl_enrichment_rcpp",      (DL_FUNC) &_pecotmr_qtl_enrichment_rcpp,       9},
    {"_pecotmr_sdpr_rcpp",                (DL_FUNC) &_pecotmr_sdpr_rcpp,                17},
    {NULL, NULL, 0}
};
}

extern "C" attribute_visible void R_init_pecotmr(DllInfo* dll){
  R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
  R_useDynamicSymbols(dll, FALSE);
  R_forceSymbols(dll, TRUE);
}
