# Generated by cpp11: do not edit by hand

dentistIterativeImpute <- function(ldMatR, nSample, zScoreR, pValueThreshold, propSVD, gcControl, nIter, gPvalueThreshold, ncpus, correctChenEtAlBug, verbose) {
  .Call(`_pecotmr_dentistIterativeImpute`, ldMatR, nSample, zScoreR, pValueThreshold, propSVD, gcControl, nIter, gPvalueThreshold, ncpus, correctChenEtAlBug, verbose)
}

lassosumRssRcpp <- function(zR, LD, lambdaR, thr, maxiter) {
  .Call(`_pecotmr_lassosumRssRcpp`, zR, LD, lambdaR, thr, maxiter)
}

penalizedRssRcpp <- function(zR, LD, lambdaR, penaltyStr, gamma, alpha, lambda0, lambda2, thr, maxiter, maxSwaps) {
  .Call(`_pecotmr_penalizedRssRcpp`, zR, LD, lambdaR, penaltyStr, gamma, alpha, lambda0, lambda2, thr, maxiter, maxSwaps)
}

prsCsRcpp <- function(a, b, phi, bhat, maf, n, ldBlk, nIter, nBurnin, thin, verbose, seed) {
  .Call(`_pecotmr_prsCsRcpp`, a, b, phi, bhat, maf, n, ldBlk, nIter, nBurnin, thin, verbose, seed)
}

qtlEnrichmentRcpp <- function(rGwasPip, rQtlSusieFit, piGwas, piQtl, ImpN, shrinkageLambda, doubleShrinkage, besselCorrection, numThreads) {
  .Call(`_pecotmr_qtlEnrichmentRcpp`, rGwasPip, rQtlSusieFit, piGwas, piQtl, ImpN, shrinkageLambda, doubleShrinkage, besselCorrection, numThreads)
}

sdprRcpp <- function(bhatR, LD, n, perVariantSampleSize, array, a, c, M, a0k, b0k, iter, burn, thin, nThreads, optLlk, verbose, seed) {
  .Call(`_pecotmr_sdprRcpp`, bhatR, LD, n, perVariantSampleSize, array, a, c, M, a0k, b0k, iter, burn, thin, nThreads, optLlk, verbose, seed)
}
