#' Preprocess input data for RSS analysis
#'
#' This function preprocesses summary statistics and LD data for RSS analysis.
#' It performs allele quality control, flipping alleles as necessary, and removes
#' specified regions from the analysis.
#'
#' @param sumstats A data frame containing summary statistics with columns "chrom", "pos", "A1", and "A2".
#' @param LD_data A list containing combined LD variants data that is generated by load_LD_matrix.
#' @param skip_region A character vector specifying regions to be skipped in the analysis (optional).
#'                    Each region should be in the format "chrom:start-end" (e.g., "1:1000000-2000000").
#' @param return_LD_mat Logical; if \code{FALSE}, return only harmonized
#'   summary statistics and skip LD-matrix subsetting. This is useful when the
#'   reference input is genotype-backed \code{X_ref}. Defaults to \code{TRUE}
#'   for backwards compatibility.
#'
#' @return A list containing the processed summary statistics and LD matrix.
#'   - sumstats: A data frame containing the processed summary statistics.
#'   - LD_mat: The processed LD matrix.
#'
#' @importFrom dplyr filter pull arrange
#' @importFrom tibble tibble
#' @importFrom tidyr separate
#' @importFrom magrittr %>%
#' @export
rss_basic_qc <- function(sumstats, LD_data, skip_region = NULL, keep_indel = TRUE,
                         return_LD_mat = TRUE) {
  # Check if required columns are present in sumstats
  required_cols <- c("chrom", "pos", "A1", "A2")
  missing_cols <- setdiff(required_cols, colnames(sumstats))
  if (length(missing_cols) > 0) {
    stop("Missing columns in sumstats: ", paste(missing_cols, collapse = ", "))
  }

  # Dynamically detect which effect columns exist to flip
  # Must have at least one of beta or z
  flip_candidates <- c("beta", "z")
  col_to_flip <- intersect(flip_candidates, colnames(sumstats))
  if (length(col_to_flip) == 0) {
    stop("sumstats must contain at least one of: 'beta', 'z'")
  }

  ref_variants <- LD_data$LD_variants

  allele_flip <- match_ref_panel(sumstats, ref_variants,
    col_to_flip = col_to_flip,
    match_min_prop = 0, remove_dups = TRUE, remove_indels = !keep_indel,
    remove_strand_ambiguous = TRUE
  )

  if (!is.null(skip_region)) {
    skip_table <- tibble(region = skip_region) %>%
      separate(region, into = c("chrom", "start", "end"), sep = "[-:]") %>%
      mutate(start = as.integer(start), end = as.integer(end))

    skip_variant <- c()
    for (region_index in 1:nrow(skip_table)) {
      variant <- allele_flip$target_data_qced %>%
        filter(chrom == skip_table$chrom[region_index] &
          pos > skip_table$start[region_index] &
          pos < skip_table$end[region_index]) %>%
        pull(variant_id)
      skip_variant <- c(skip_variant, variant)
    }

    allele_flip$target_data_qced <- allele_flip$target_data_qced %>%
      filter(!(variant_id %in% skip_variant))
  }

  sumstats_processed <- allele_flip$target_data_qced %>% arrange(pos)

  if (!isTRUE(return_LD_mat)) {
    return(list(sumstats = sumstats_processed, LD_mat = NULL))
  }

  # Align and subset LD by mapping core IDs (strip trailing build suffix) to exact LD IDs
  ld_mat <- LD_data$LD_matrix
  ld_ids <- tryCatch(rownames(ld_mat), error = function(e) NULL)
  if (is.null(ld_ids)) {
    stop("LD matrix rownames are NULL; cannot align variant IDs.")
  }
  present <- sumstats_processed$variant_id %in% ld_ids
  if (sum(present) == 0) {
    ld_core <- strip_chr_prefix(strip_build_suffix(ld_ids))
    ss_core <- strip_chr_prefix(strip_build_suffix(sumstats_processed$variant_id))
    map_idx <- match(ss_core, ld_core)
    remap <- !is.na(map_idx)
    if (sum(remap) > 0) {
      sumstats_processed$variant_id[remap] <- ld_ids[map_idx[remap]]
      present <- sumstats_processed$variant_id %in% ld_ids
    }
  }
  if (sum(present) == 0) {
    stop("No overlapping variants between sumstats and LD after alignment.")
  }

  LD_mat_processed <- LD_data$LD_matrix[sumstats_processed$variant_id, sumstats_processed$variant_id, drop = FALSE]

  return(list(sumstats = sumstats_processed, LD_mat = LD_mat_processed))
}


#' Detect LD-Summary Statistic Mismatches
#'
#' Unified wrapper for detecting outlier variants due to LD-summary statistic
#' mismatches. Dispatches to either \code{\link{dentist_single_window}} or
#' \code{\link{slalom}} based on the \code{method} argument.
#'
#' @param zScore Numeric vector of z-scores.
#' @param R Square LD correlation matrix. Provide either \code{R} or \code{X}.
#' @param X Genotype matrix (samples x SNPs). If provided, LD is computed via
#'   \code{\link{compute_LD}} and \code{nSample} defaults to \code{nrow(X)}.
#' @param nSample Number of samples in the LD reference panel. Required when
#'   \code{R} is provided and \code{method = "dentist"}; inferred from \code{X}
#'   when \code{X} is provided.
#' @param method Character string specifying the QC method: \code{"slalom"}
#'   (default) or \code{"dentist"}.
#' @param ld_method Character string specifying the LD computation method when
#'   \code{X} is provided. One of \code{"sample"} (default), \code{"population"},
#'   or \code{"gcta"}. Ignored when \code{R} is provided directly.
#' @param ... Additional arguments passed to the underlying QC method
#'   (\code{\link{dentist_single_window}} or \code{\link{slalom}}).
#'
#' @return A data frame with at least a logical \code{outlier} column indicating
#'   which variants are identified as outliers. The remaining columns depend on
#'   the method used.
#'
#' @seealso \code{\link{dentist_single_window}}, \code{\link{slalom}},
#'   \code{\link{summary_stats_qc}}
#' @importFrom dplyr mutate row_number filter pull
#' @export
ld_mismatch_qc <- function(zScore, R = NULL, X = NULL, nSample = NULL,
                           method = c("slalom", "dentist"),
                           ld_method = "sample", ...) {
  method <- match.arg(method)
  if (method == "dentist") {
    qc_results <- dentist_single_window(zScore, R = R, X = X, nSample = nSample,
                                        ld_method = ld_method, ...)
    return(qc_results)
  } else {
    qc_results <- slalom(zScore, R = R, X = X, ld_method = ld_method, ...)
    # Standardize output: slalom uses "outliers", rename to "outlier" for consistency
    result <- qc_results$data
    if ("outliers" %in% colnames(result) && !"outlier" %in% colnames(result)) {
      colnames(result)[colnames(result) == "outliers"] <- "outlier"
    }
    return(result)
  }
}

.resolve_summary_qc_method <- function(qc_method) {
  if (is.null(qc_method)) return("none")
  match.arg(qc_method, c("none", "slalom", "dentist"))
}

#' Perform Quality Control on Summary Statistics
#'
#' This function performs quality control on the processed summary statistics
#' using the specified method. It wraps \code{\link{ld_mismatch_qc}} and handles
#' subsetting of the summary statistics and LD matrix.
#'
#' @param sumstats A data frame containing the processed summary statistics.
#' @param LD_data A list containing the combined LD variants data generated by
#'   \code{load_LD_matrix()}.
#' @param n Sample size for the LD reference panel (used by dentist method).
#' @param method The quality control method to use. Options are \code{"slalom"}
#'   or \code{"dentist"} (default: \code{"slalom"}).
#' @param rss_input Optional loaded RSS input, either one \code{load_rss_data()}
#'   result or a named list of them. Supplying this selects the additional
#'   combined RSS/ColocBoost QC workflow. A single RSS record is detected by
#'   structure, not by the name \code{sumstats}, so a multi-study list may safely
#'   include a study named \code{"sumstats"}.
#' @param keep_indel,skip_region,pip_cutoff_to_skip,qc_method,impute,impute_opts,study,var_y,return_on_skip,R_finite,R_mismatch
#'   Additional controls for the combined RSS/ColocBoost QC workflow. They are
#'   ignored by the historical LD-mismatch-only call unless \code{rss_input} or
#'   combined-QC options are supplied.
#'
#' @return A list containing the quality-controlled summary statistics and
#'   updated LD matrix for the historical call:
#'   \itemize{
#'     \item sumstats: The quality-controlled summary statistics data frame.
#'     \item LD_mat: The updated LD matrix after quality control.
#'     \item outlier_number: The number of outlier variants removed.
#'   }
#'   When \code{rss_input} or combined-QC controls are supplied, returns a
#'   cleaned RSS/LD record for one RSS record, or a named list of records for a
#'   list of RSS records.
#'
#' @details This function applies the specified quality control method to the
#'   processed summary statistics via \code{\link{ld_mismatch_qc}}, then subsets
#'   the summary statistics and LD matrix to keep only non-outlier variants.
#'
#'   As an additional workflow for ColocBoost/RSS pipelines, callers may supply
#'   \code{rss_input} or combined-QC controls. That path first runs
#'   \code{rss_basic_qc()}, optional PIP screening, optional LD-mismatch QC
#'   through this same function, and optional RAISS imputation. The combined
#'   path normalizes one or many RSS records to the same loop internally; only
#'   true single-record input is unwrapped on return.
#'   \code{qc_method = NULL} and \code{"none"} mean basic-only summary-stat
#'   preprocessing without SLALOM/DENTIST outlier QC.
#'
#'   When the combined path receives genotype-backed reference data
#'   (\code{X_ref}), basic harmonization avoids constructing an LD matrix. PIP
#'   screening uses an LD-independent single-effect screen with
#'   \code{susie_rss(R = diag(p), L = 1, max_iter = 1)}, and LD-mismatch QC
#'   computes only the filtered local correlation matrix required by
#'   SLALOM/DENTIST. RAISS imputation temporarily centers/scales
#'   genotype-backed \code{X_ref} before using the whole-region genotype/SVD
#'   path. This avoids LD-block partition artifacts while matching the LD scale
#'   used by \code{compute_LD(X_ref)}. Final ColocBoost calls still keep the
#'   original \code{X_ref} as the reference input.
#'
#' @examples
#' # Perform SLALOM quality control (default)
#' qc_results <- summary_stats_qc(sumstats, LD_data, method = "slalom")
#'
#' # Additional combined basic-only RSS QC.
#' qc_results <- summary_stats_qc(rss_input = rss_input, LD_data = LD_data,
#'                                qc_method = "none")
#'
#' @importFrom dplyr mutate row_number filter pull
#' @export
summary_stats_qc <- function(sumstats, LD_data, n = NULL,
                             method = c("slalom", "dentist"),
                             rss_input = NULL,
                             keep_indel = TRUE,
                             skip_region = NULL,
                             pip_cutoff_to_skip = 0,
                             qc_method = NULL,
                             impute = FALSE,
                             impute_opts = list(rcond = 0.01, R2_threshold = 0.6,
                                                minimum_ld = 5, lamb = 0.01),
                             study = NULL,
                             var_y = NULL,
                             return_on_skip = c("null", "preprocess"),
                             R_finite = NULL,
                             R_mismatch = NULL) {
  if (missing(sumstats)) sumstats <- NULL
  return_on_skip <- match.arg(return_on_skip)
  if (is.null(rss_input) && is.data.frame(sumstats) && is.null(qc_method) &&
      isFALSE(impute) && identical(pip_cutoff_to_skip, 0) && is.null(skip_region)) {
    method <- match.arg(method)
    LD_extract <- LD_data$LD_matrix[sumstats$variant_id, sumstats$variant_id, drop = FALSE]
    qc_results <- ld_mismatch_qc(zScore = sumstats$z, R = LD_extract,
                                 nSample = n, method = method)
    keep_index <- which(!qc_results$outlier)
    sumstats_qc <- sumstats[keep_index, , drop = FALSE]
    LD_mat_qc <- LD_extract[sumstats_qc$variant_id, sumstats_qc$variant_id, drop = FALSE]
    outlier_number <- nrow(sumstats) - nrow(sumstats_qc)
    return(list(sumstats = sumstats_qc, LD_mat = LD_mat_qc, outlier_number = outlier_number))
  }

  qc_method <- .resolve_summary_qc_method(qc_method)

  if (is.null(rss_input)) {
    if (is.null(sumstats)) stop("summary_stats_qc requires sumstats or rss_input.")
    rss_input <- if (is.data.frame(sumstats)) {
      list(sumstats = sumstats, n = n, var_y = if (is.null(var_y)) 1 else var_y)
    } else {
      sumstats
    }
  }

  is_rss_record <- function(x) {
    is.list(x) && is.data.frame(x$sumstats)
  }
  is_ld_record <- function(x) {
    is.matrix(x) || (is.list(x) && !is.null(x$LD_matrix))
  }
  first_ld_record <- function(x, study_name = NULL) {
    if (is_ld_record(x)) return(x)
    if (!is.null(study_name) && study_name %in% names(x)) return(x[[study_name]])
    if (is.list(x) && length(x) == 1) return(x[[1]])
    x
  }

  single_rss_input <- is_rss_record(rss_input)
  if (single_rss_input) {
    studies <- if (is.null(study)) "input" else study
    rss_records <- stats::setNames(list(rss_input), studies)
    LD_records <- stats::setNames(list(first_ld_record(LD_data, studies)), studies)
  } else {
    if (!is.list(rss_input) || length(rss_input) == 0) {
      stop("No summary-statistic studies supplied for QC.")
    }
    rss_records <- rss_input
    studies <- names(rss_records)
    if (is.null(studies)) studies <- rep("", length(rss_records))
    empty_names <- is.na(studies) | studies == ""
    if (any(empty_names)) {
      studies[empty_names] <- paste0("study", which(empty_names))
      names(rss_records) <- studies
    }
    if (!all(vapply(rss_records, is_rss_record, logical(1)))) {
      stop("rss_input must be one RSS record or a list of RSS records with a sumstats data frame.")
    }

    if (is_ld_record(LD_data)) {
      LD_records <- stats::setNames(rep(list(LD_data), length(studies)), studies)
    } else if (is.list(LD_data) && length(LD_data) == 1) {
      LD_records <- stats::setNames(rep(list(LD_data[[1]]), length(studies)), studies)
    } else if (is.list(LD_data) && all(studies %in% names(LD_data))) {
      LD_records <- LD_data[studies]
    } else if (is.list(LD_data) && length(LD_data) == length(studies)) {
      LD_records <- LD_data
      names(LD_records) <- studies
    } else {
      stop("LD_data must be one LD object or a list matching rss_input studies.")
    }
  }

  if (length(pip_cutoff_to_skip) == 1 && is.null(names(pip_cutoff_to_skip))) {
    cutoffs <- stats::setNames(rep(pip_cutoff_to_skip, length(studies)), studies)
  } else if (!is.null(names(pip_cutoff_to_skip))) {
    missing <- setdiff(studies, names(pip_cutoff_to_skip))
    if (length(missing) > 0) {
      pip_cutoff_to_skip <- c(pip_cutoff_to_skip, stats::setNames(rep(0, length(missing)), missing))
    }
    cutoffs <- pip_cutoff_to_skip[studies]
  } else if (length(pip_cutoff_to_skip) == length(studies)) {
    cutoffs <- stats::setNames(pip_cutoff_to_skip, studies)
  } else {
    stop("pip_cutoff_to_skip must be a scalar, named vector, or match the number of studies.")
  }

  out <- list()
  for (study_name in studies) {
    result <- .summary_stats_qc_single_study(
      rss_records[[study_name]], LD_records[[study_name]],
      keep_indel = keep_indel,
      skip_region = skip_region,
      pip_cutoff_to_skip = cutoffs[[study_name]],
      qc_method = qc_method,
      impute = impute,
      impute_opts = impute_opts,
      study = study_name,
      return_on_skip = return_on_skip,
      R_finite = R_finite,
      R_mismatch = R_mismatch
    )
    if (!is.null(result)) out[[study_name]] <- result
  }
  if (single_rss_input) out[[studies]] else out
}

.infer_single_ld_block_metadata <- function(ref_panel) {
  n_variants <- nrow(ref_panel)
  data.frame(
    block_id = 1L,
    chrom = as.character(ref_panel$chrom[1]),
    block_start = suppressWarnings(min(ref_panel$pos, na.rm = TRUE)),
    block_end = suppressWarnings(max(ref_panel$pos, na.rm = TRUE)),
    size = n_variants,
    start_idx = 1L,
    end_idx = n_variants,
    stringsAsFactors = FALSE
  )
}

.normalize_ld_data_for_qc <- function(LD_data) {
  if (is.null(LD_data)) return(NULL)
  if (is.matrix(LD_data)) {
    ids <- if (nrow(LD_data) == ncol(LD_data)) rownames(LD_data) else colnames(LD_data)
    LD_data <- list(LD_matrix = LD_data, LD_variants = ids)
  }
  if (is.data.frame(LD_data$LD_variants)) {
    variant_ids <- if ("variant_id" %in% colnames(LD_data$LD_variants)) {
      as.character(LD_data$LD_variants$variant_id)
    } else {
      format_variant_id(LD_data$LD_variants$chrom, LD_data$LD_variants$pos,
                        LD_data$LD_variants$A2, LD_data$LD_variants$A1)
    }
    LD_data$LD_variants <- variant_ids
  }
  if (is.data.frame(LD_data$ref_panel) && !"variant_id" %in% colnames(LD_data$ref_panel)) {
    LD_data$ref_panel$variant_id <- format_variant_id(
      LD_data$ref_panel$chrom, LD_data$ref_panel$pos,
      LD_data$ref_panel$A2, LD_data$ref_panel$A1
    )
  }
  if (is.null(LD_data$LD_variants) && is.data.frame(LD_data$ref_panel) &&
      "variant_id" %in% colnames(LD_data$ref_panel)) {
    LD_data$LD_variants <- as.character(LD_data$ref_panel$variant_id)
  }
  if (is.null(LD_data$ref_panel) && !is.null(LD_data$LD_variants)) {
    parsed <- tryCatch(parse_variant_id(LD_data$LD_variants), error = function(e) NULL)
    if (!is.null(parsed)) {
      LD_data$ref_panel <- parsed
      LD_data$ref_panel$variant_id <- LD_data$LD_variants
    }
  }
  if (!is.null(LD_data$LD_variants) && is.matrix(LD_data$LD_matrix)) {
    if (nrow(LD_data$LD_matrix) == ncol(LD_data$LD_matrix) &&
        length(LD_data$LD_variants) == nrow(LD_data$LD_matrix)) {
      rownames(LD_data$LD_matrix) <- colnames(LD_data$LD_matrix) <- LD_data$LD_variants
    } else if (length(LD_data$LD_variants) == ncol(LD_data$LD_matrix)) {
      colnames(LD_data$LD_matrix) <- LD_data$LD_variants
    }
  }
  LD_data
}

.summary_stats_qc_single_study <- function(rss_input, LD_data, keep_indel, skip_region,
                                           pip_cutoff_to_skip, qc_method, impute,
                                           impute_opts, study, return_on_skip,
                                           R_finite = NULL, R_mismatch = NULL) {
  skipped_result <- function(sumstats, LD_mat, reason) {
    if (!identical(return_on_skip, "preprocess")) return(NULL)
    list(
      rss_input = list(sumstats = sumstats, n = rss_input$n, var_y = rss_input$var_y),
      LD_matrix = LD_mat,
      preprocess = list(sumstats = sumstats, LD_mat = LD_mat),
      outlier_number = 0L,
      skipped = TRUE,
      skip_reason = reason
    )
  }

  if (is.null(rss_input) || is.null(LD_data)) return(NULL)
  message("QC track: starting basic allele harmonization for summary-stat study ", study, ".")
  message("QC track: basic summary-stat QC requires sumstat$variant and LD_data$LD_variants ",
          "or LD/X_ref variant names for study ", study, ".")
  LD_data_for_qc <- .normalize_ld_data_for_qc(LD_data)
  has_genotype <- isTRUE(LD_data_for_qc$is_genotype) ||
    (is.matrix(LD_data_for_qc$LD_matrix) &&
       nrow(LD_data_for_qc$LD_matrix) != ncol(LD_data_for_qc$LD_matrix))
  if (has_genotype && is.data.frame(LD_data_for_qc$ref_panel) &&
      all(c("chrom", "pos", "A2", "A1") %in% colnames(LD_data_for_qc$ref_panel))) {
    canonical_ids <- format_variant_id(LD_data_for_qc$ref_panel$chrom,
                                       LD_data_for_qc$ref_panel$pos,
                                       LD_data_for_qc$ref_panel$A2,
                                       LD_data_for_qc$ref_panel$A1)
    LD_data_for_qc$ref_panel$variant_id <- canonical_ids
    LD_data_for_qc$LD_variants <- canonical_ids
    if (is.matrix(LD_data_for_qc$LD_matrix) &&
        length(canonical_ids) == ncol(LD_data_for_qc$LD_matrix)) {
      colnames(LD_data_for_qc$LD_matrix) <- canonical_ids
    }
  }
  X_ref <- if (has_genotype) LD_data_for_qc$LD_matrix else NULL
  basic <- rss_basic_qc(rss_input$sumstats, LD_data_for_qc,
                        skip_region = skip_region, keep_indel = keep_indel,
                        return_LD_mat = !has_genotype)
  sumstats <- basic$sumstats
  R_mat <- basic$LD_mat
  n <- rss_input$n
  var_y <- rss_input$var_y
  reference_for_variants <- function(variants) {
    if (has_genotype) {
      ref_names <- colnames(X_ref)
      ref_idx <- match(variants, ref_names)
      if (anyNA(ref_idx)) {
        ref_idx <- match(strip_chr_prefix(strip_build_suffix(variants)),
                         strip_chr_prefix(strip_build_suffix(ref_names)))
      }
      if (anyNA(ref_idx)) {
        missing_variants <- variants[is.na(ref_idx)]
        stop("Genotype reference is missing ", length(missing_variants),
             " post-QC variant(s): ", paste(utils::head(missing_variants, 3), collapse = ", "))
      }
      X_subset <- X_ref[, ref_idx, drop = FALSE]
      colnames(X_subset) <- variants
      return(X_subset)
    }
    if (is.null(R_mat)) return(NULL)
    R_mat[variants, variants, drop = FALSE]
  }
  ld_data_with_local_R <- function(current_sumstats) {
    if (!has_genotype) return(LD_data_for_qc)
    variants <- current_sumstats$variant_id
    X_local <- reference_for_variants(variants)
    R_local <- compute_LD(X_local, method = "sample")
    rownames(R_local) <- colnames(R_local) <- variants
    ref_panel <- LD_data_for_qc$ref_panel
    if (is.data.frame(ref_panel) && "variant_id" %in% colnames(ref_panel)) {
      ref_idx <- match(variants, ref_panel$variant_id)
      if (anyNA(ref_idx)) {
        ref_panel <- parse_variant_id(variants)
        ref_panel$variant_id <- variants
      } else {
        ref_panel <- ref_panel[ref_idx, , drop = FALSE]
      }
    } else {
      ref_panel <- parse_variant_id(variants)
      ref_panel$variant_id <- variants
    }
    ld_data <- LD_data_for_qc
    ld_data$LD_matrix <- R_local
    ld_data$LD_variants <- variants
    ld_data$ref_panel <- ref_panel
    ld_data$block_metadata <- .infer_single_ld_block_metadata(ref_panel)
    ld_data$is_genotype <- FALSE
    R_mat <<- R_local
    ld_data
  }
  message("QC track: basic harmonization retained ", nrow(sumstats),
          " variants for summary-stat study ", study, ".")
  if (nrow(sumstats) < 2) {
    return(skipped_result(sumstats, reference_for_variants(sumstats$variant_id),
                          "fewer than two variants remain after basic QC"))
  }

  preprocess <- list(sumstats = sumstats, LD_mat = R_mat)
  if (!is.null(pip_cutoff_to_skip) && pip_cutoff_to_skip != 0) {
    cutoff <- pip_cutoff_to_skip
    if (cutoff < 0) cutoff <- 3 / nrow(sumstats)
    message("QC track: running LD-independent single-effect initial screen for summary-stat study ",
            study, ".")
    pip_args <- list(z = sumstats$z, R = diag(nrow(sumstats)),
                     L = 1, max_iter = 1, n = n)
    pip <- do.call(susie_rss, pip_args)$pip
    if (!any(pip > cutoff)) {
      message("Skipping follow-up analysis: No signals above PIP threshold ", cutoff)
      message("QC track: skipping summary-stat study ", study,
              ". No signals above PIP threshold ", cutoff, ".")
      return(skipped_result(sumstats, reference_for_variants(sumstats$variant_id),
                            "no signals above PIP threshold"))
    }
    message("Follow-up on region: signals above PIP threshold ", cutoff, " detected.")
  }

  outlier_number <- 0L
  if (!is.null(qc_method) && !identical(qc_method, "none")) {
    message("QC track: running ", qc_method, " LD-mismatch QC for summary-stat study ", study, ".")
    qc <- summary_stats_qc(sumstats = sumstats, LD_data = ld_data_with_local_R(sumstats),
                            n = n, method = qc_method)
    sumstats <- qc$sumstats
    R_mat <- qc$LD_mat
    outlier_number <- qc$outlier_number
    message("QC track: removed ", outlier_number,
            " LD-mismatch outlier(s) for summary-stat study ", study, ".")
  }
  if (isTRUE(impute)) {
    if (is.null(LD_data_for_qc$ref_panel)) {
      warning("Skipping imputation for summary-stat study ", study,
              ": LD_data does not include ref_panel.")
    } else {
      message("QC track: running imputation for summary-stat study ", study, ".")
      imputed <- if (has_genotype) {
        X_ref_scaled <- scale(X_ref)
        X_ref_scaled[is.na(X_ref_scaled)] <- 0
        colnames(X_ref_scaled) <- colnames(X_ref)
        raiss(LD_data_for_qc$ref_panel, sumstats,
              genotype_matrix = X_ref_scaled,
              svd_tol = if (is.null(impute_opts$svd_tol)) 1e-12 else impute_opts$svd_tol,
              R2_threshold = impute_opts$R2_threshold,
              minimum_ld = impute_opts$minimum_ld,
              lamb = impute_opts$lamb)
      } else {
        if (is.null(LD_data_for_qc$block_metadata)) {
          LD_data_for_qc$block_metadata <- .infer_single_ld_block_metadata(LD_data_for_qc$ref_panel)
        }
        raiss(LD_data_for_qc$ref_panel, sumstats, partition_LD_matrix(LD_data_for_qc),
              rcond = impute_opts$rcond,
              R2_threshold = impute_opts$R2_threshold,
              minimum_ld = impute_opts$minimum_ld,
              lamb = impute_opts$lamb)
      }
      sumstats <- imputed$result_filter
      if (!is.null(imputed$LD_mat)) R_mat <- imputed$LD_mat
    }
  }
  final_vars <- sumstats$variant_id
  list(
    rss_input = list(sumstats = sumstats, n = n, var_y = var_y),
    LD_matrix = if (has_genotype) reference_for_variants(final_vars) else R_mat,
    preprocess = preprocess,
    outlier_number = outlier_number,
    skipped = FALSE
  )
}
