#' Preprocess input data for RSS analysis
#'
#' This function preprocesses summary statistics and LD data for RSS analysis.
#' It performs allele quality control, flipping alleles as necessary, and removes
#' specified regions from the analysis.
#'
#' @param sumstats A data frame containing summary statistics with columns "chrom", "pos", "A1", and "A2".
#' @param LD_data A list containing combined LD variants data that is generated by load_LD_matrix.
#' @param skip_region A character vector specifying regions to be skipped in the analysis (optional).
#'                    Each region should be in the format "chrom:start-end" (e.g., "1:1000000-2000000").
#'
#' @return A list containing the processed summary statistics and LD matrix.
#'   - sumstats: A data frame containing the processed summary statistics.
#'   - LD_mat: The processed LD matrix.
#'
#' @importFrom dplyr filter pull arrange
#' @importFrom tibble tibble
#' @importFrom tidyr separate
#' @importFrom magrittr %>%
#' @export
rss_basic_qc <- function(sumstats, LD_data, skip_region = NULL, keep_indel = TRUE) {
  # Check if required columns are present in sumstats
  required_cols <- c("chrom", "pos", "A1", "A2")
  missing_cols <- setdiff(required_cols, colnames(sumstats))
  if (length(missing_cols) > 0) {
    stop("Missing columns in sumstats: ", paste(missing_cols, collapse = ", "))
  }

  # Dynamically detect which effect columns exist to flip
  # Must have at least one of beta or z
  flip_candidates <- c("beta", "z")
  col_to_flip <- intersect(flip_candidates, colnames(sumstats))
  if (length(col_to_flip) == 0) {
    stop("sumstats must contain at least one of: 'beta', 'z'")
  }

  ref_variants <- LD_data$LD_variants

  allele_flip <- allele_qc(sumstats, ref_variants,
    col_to_flip = col_to_flip,
    match_min_prop = 0, remove_dups = TRUE, remove_indels = !keep_indel,
    remove_strand_ambiguous = TRUE
  )

  if (!is.null(skip_region)) {
    skip_table <- tibble(region = skip_region) %>%
      separate(region, into = c("chrom", "start", "end"), sep = "[-:]") %>%
      mutate(start = as.integer(start), end = as.integer(end))

    skip_variant <- c()
    for (region_index in 1:nrow(skip_table)) {
      variant <- allele_flip$target_data_qced %>%
        filter(chrom == skip_table$chrom[region_index] &
          pos > skip_table$start[region_index] &
          pos < skip_table$end[region_index]) %>%
        pull(variant_id)
      skip_variant <- c(skip_variant, variant)
    }

    allele_flip$target_data_qced <- allele_flip$target_data_qced %>%
      filter(!(variant_id %in% skip_variant))
  }

  sumstats_processed <- allele_flip$target_data_qced %>% arrange(pos)

  # Align and subset LD by mapping core IDs (strip trailing build suffix) to exact LD IDs
  ld_mat <- LD_data$LD_matrix
  ld_ids <- tryCatch(rownames(ld_mat), error = function(e) NULL)
  if (is.null(ld_ids)) {
    stop("LD matrix rownames are NULL; cannot align variant IDs.")
  }
  present <- sumstats_processed$variant_id %in% ld_ids
  if (sum(present) == 0) {
    ld_core <- strip_chr_prefix(strip_build_suffix(ld_ids))
    ss_core <- strip_chr_prefix(strip_build_suffix(sumstats_processed$variant_id))
    map_idx <- match(ss_core, ld_core)
    remap <- !is.na(map_idx)
    if (sum(remap) > 0) {
      sumstats_processed$variant_id[remap] <- ld_ids[map_idx[remap]]
      present <- sumstats_processed$variant_id %in% ld_ids
    }
  }
  if (sum(present) == 0) {
    stop("No overlapping variants between sumstats and LD after alignment.")
  }

  LD_mat_processed <- LD_data$LD_matrix[sumstats_processed$variant_id, sumstats_processed$variant_id, drop = FALSE]

  return(list(sumstats = sumstats_processed, LD_mat = LD_mat_processed))
}


#' Detect LD-Summary Statistic Mismatches
#'
#' Unified wrapper for detecting outlier variants due to LD-summary statistic
#' mismatches. Dispatches to either \code{\link{dentist_single_window}} or
#' \code{\link{slalom}} based on the \code{method} argument.
#'
#' @param zScore Numeric vector of z-scores.
#' @param R Square LD correlation matrix. Provide either \code{R} or \code{X}.
#' @param X Genotype matrix (samples x SNPs). If provided, LD is computed via
#'   \code{\link{compute_LD}} and \code{nSample} defaults to \code{nrow(X)}.
#' @param nSample Number of samples in the LD reference panel. Required when
#'   \code{R} is provided and \code{method = "dentist"}; inferred from \code{X}
#'   when \code{X} is provided.
#' @param method Character string specifying the QC method: \code{"slalom"}
#'   (default) or \code{"dentist"}.
#' @param ld_method Character string specifying the LD computation method when
#'   \code{X} is provided. One of \code{"sample"} (default), \code{"population"},
#'   or \code{"gcta"}. Ignored when \code{R} is provided directly.
#' @param ... Additional arguments passed to the underlying QC method
#'   (\code{\link{dentist_single_window}} or \code{\link{slalom}}).
#'
#' @return A data frame with at least a logical \code{outlier} column indicating
#'   which variants are identified as outliers. The remaining columns depend on
#'   the method used.
#'
#' @seealso \code{\link{dentist_single_window}}, \code{\link{slalom}},
#'   \code{\link{summary_stats_qc}}
#' @importFrom dplyr mutate row_number filter pull
#' @export
ld_mismatch_qc <- function(zScore, R = NULL, X = NULL, nSample = NULL,
                           method = c("slalom", "dentist"),
                           ld_method = "sample", ...) {
  method <- match.arg(method)
  if (method == "dentist") {
    qc_results <- dentist_single_window(zScore, R = R, X = X, nSample = nSample,
                                        ld_method = ld_method, ...)
    return(qc_results)
  } else {
    qc_results <- slalom(zScore, R = R, X = X, ld_method = ld_method, ...)
    # Standardize output: slalom uses "outliers", rename to "outlier" for consistency
    result <- qc_results$data
    if ("outliers" %in% colnames(result) && !"outlier" %in% colnames(result)) {
      colnames(result)[colnames(result) == "outliers"] <- "outlier"
    }
    return(result)
  }
}

#' Perform Quality Control on Summary Statistics
#'
#' This function performs quality control on the processed summary statistics using the specified method.
#' It wraps \code{\link{ld_mismatch_qc}} and handles subsetting of the summary statistics and LD matrix.
#'
#' @param sumstats A data frame containing the processed summary statistics.
#' @param LD_data A list containing the combined LD variants data generated by load_LD_matrix.
#' @param n Sample size for the LD reference panel (used by dentist method).
#' @param method The quality control method to use. Options are "slalom" or "dentist" (default: "slalom").
#'
#' @return A list containing the quality-controlled summary statistics and updated LD matrix.
#'   - sumstats: The quality-controlled summary statistics data frame.
#'   - LD_mat: The updated LD matrix after quality control.
#'   - outlier_number: The number of outlier variants removed.
#'
#' @details This function applies the specified quality control method to the processed summary statistics
#'   via \code{\link{ld_mismatch_qc}}, then subsets the summary statistics and LD matrix to keep
#'   only non-outlier variants.
#'
#' @examples
#' # Perform SLALOM quality control (default)
#' qc_results <- summary_stats_qc(sumstats, LD_data, method = "slalom")
#'
#' @importFrom dplyr mutate row_number filter pull
#' @export
summary_stats_qc <- function(sumstats, LD_data, n = NULL, method = c("slalom", "dentist")) {
  method <- match.arg(method)
  LD_extract <- LD_data$LD_matrix[sumstats$variant_id, sumstats$variant_id, drop = FALSE]

  qc_results <- ld_mismatch_qc(zScore = sumstats$z, R = LD_extract, nSample = n,
                                method = method)
  keep_index <- which(!qc_results$outlier)
  sumstats_qc <- sumstats[keep_index, , drop = FALSE]
  LD_mat_qc <- LD_extract[sumstats_qc$variant_id, sumstats_qc$variant_id, drop = FALSE]
  outlier_number <- nrow(sumstats) - nrow(sumstats_qc)

  return(list(sumstats = sumstats_qc, LD_mat = LD_mat_qc, outlier_number = outlier_number))
}
