#' Preprocess input data for RSS analysis
#'
#' This function preprocesses summary statistics and LD data for RSS analysis.
#' It performs allele quality control, flipping alleles as necessary, and removes
#' specified regions from the analysis.
#'
#' @param sumstats A data frame containing summary statistics with columns "chrom", "pos", "A1", and "A2".
#' @param ldData An \code{LdData} S4 object containing combined LD variants
#'   data, as generated by \code{loadLdMatrix}.
#' @param skipRegion A character vector specifying regions to be skipped in the analysis (optional).
#'                   Each region should be in the format "chrom:start-end" (e.g., "1:1000000-2000000").
#' @param returnLdMat Logical; if \code{FALSE}, the returned \code{QcResult}
#'   carries \code{NULL} in its \code{ldData} slot (no LD subsetting is
#'   performed). Useful when the reference input is genotype-backed.
#'
#' @return A \code{QcResult} S4 object. Use \code{getRssInput()$sumstats} to
#'   recover the harmonized sumstats and \code{getCorrelation(getLdData(qc))}
#'   to recover the aligned LD matrix (or NULL when \code{returnLdMat=FALSE}).
#'
#' @importFrom dplyr filter pull arrange
#' @importFrom tibble tibble
#' @importFrom tidyr separate
#' @importFrom magrittr %>%
#' @export
rssBasicQc <- function(sumstats, ldData, skipRegion = NULL, keepIndel = TRUE,
                       returnLdMat = TRUE) {
  if (!is(ldData, "LdData")) {
    stop("ldData must be an LdData object")
  }
  ldVariants <- getVariantIds(ldData)
  ldMatrix <- if (returnLdMat) getCorrelation(ldData) else NULL

  # Check if required columns are present in sumstats
  requiredCols <- c("chrom", "pos", "A1", "A2")
  missingCols <- setdiff(requiredCols, colnames(sumstats))
  if (length(missingCols) > 0) {
    stop("Missing columns in sumstats: ", paste(missingCols, collapse = ", "))
  }

  # Dynamically detect which effect columns exist to flip
  # Must have at least one of beta or z
  flipCandidates <- c("beta", "z")
  colToFlip <- intersect(flipCandidates, colnames(sumstats))
  if (length(colToFlip) == 0) {
    stop("sumstats must contain at least one of: 'beta', 'z'")
  }

  refVariants <- ldVariants

  # Complement af on allele swaps when present. Step 1 only populates af when it
  # is proven effect-allele frequency, so the column's presence is the signal.
  colToComplement <- intersect("af", colnames(sumstats))

  alleleFlip <- matchRefPanel(sumstats, refVariants,
    colToFlip = colToFlip,
    colToComplement = colToComplement,
    matchMinProp = 0, removeDups = TRUE, removeIndels = !keepIndel,
    removeStrandAmbiguous = TRUE
  )

  qced <- getHarmonizedData(alleleFlip)
  if (!is.null(skipRegion)) {
    skipTable <- tibble(region = skipRegion) %>%
      separate(region, into = c("chrom", "start", "end"), sep = "[-:]") %>%
      mutate(start = as.integer(start), end = as.integer(end))

    skipVariant <- c()
    for (regionIndex in 1:nrow(skipTable)) {
      variant <- qced %>%
        filter(chrom == skipTable$chrom[regionIndex] &
          pos > skipTable$start[regionIndex] &
          pos < skipTable$end[regionIndex]) %>%
        pull(variant_id)
      skipVariant <- c(skipVariant, variant)
    }

    qced <- qced %>% filter(!(variant_id %in% skipVariant))
  }

  sumstatsProcessed <- qced %>% arrange(pos)
  nRef <- ldData@nRef

  if (!isTRUE(returnLdMat)) {
    return(QcResult(
      ldData = NULL,
      rssInput = list(sumstats = sumstatsProcessed, n = NA_real_, varY = NA_real_),
      preprocess = list(),
      outlierNumber = 0L,
      skipped = FALSE
    ))
  }

  # Align and subset LD by mapping core IDs (strip trailing build suffix) to exact LD IDs
  ldMat <- ldMatrix
  ldIds <- tryCatch(rownames(ldMat), error = function(e) NULL)
  if (is.null(ldIds)) {
    stop("LD matrix rownames are NULL; cannot align variant IDs.")
  }
  present <- sumstatsProcessed$variant_id %in% ldIds
  if (sum(present) == 0) {
    ldCore <- stripChrPrefix(stripBuildSuffix(ldIds))
    ssCore <- stripChrPrefix(stripBuildSuffix(sumstatsProcessed$variant_id))
    mapIdx <- match(ssCore, ldCore)
    remap <- !is.na(mapIdx)
    if (sum(remap) > 0) {
      sumstatsProcessed$variant_id[remap] <- ldIds[mapIdx[remap]]
      present <- sumstatsProcessed$variant_id %in% ldIds
    }
  }
  if (sum(present) == 0) {
    stop("No overlapping variants between sumstats and LD after alignment.")
  }

  ldMatProcessed <- ldMatrix[sumstatsProcessed$variant_id, sumstatsProcessed$variant_id, drop = FALSE]

  QcResult(
    ldData = .qcLdDataFromMatrix(ldMatProcessed, sumstatsProcessed$variant_id,
                                 hasGenotype = FALSE, nRef = nRef),
    rssInput = list(sumstats = sumstatsProcessed, n = NA_real_, varY = NA_real_),
    preprocess = list(),
    outlierNumber = 0L,
    skipped = FALSE
  )
}


#' Detect LD-Summary Statistic Mismatches
#'
#' Unified wrapper for detecting outlier variants due to LD-summary statistic
#' mismatches. Dispatches to either \code{\link{dentistSingleWindow}} or
#' \code{\link{slalom}} based on the \code{method} argument.
#'
#' @param zScore Numeric vector of z-scores.
#' @param R Square LD correlation matrix. Provide either \code{R} or \code{X}.
#' @param X Genotype matrix (samples x SNPs). If provided, LD is computed via
#'   \code{\link{computeLd}} and \code{nSample} defaults to \code{nrow(X)}.
#' @param nSample Number of samples in the LD reference panel. Required when
#'   \code{R} is provided and \code{method = "dentist"}; inferred from \code{X}
#'   when \code{X} is provided.
#' @param method Character string specifying the QC method: \code{"slalom"}
#'   (default) or \code{"dentist"}.
#' @param ldMethod Character string specifying the LD computation method when
#'   \code{X} is provided. One of \code{"sample"} (default), \code{"population"},
#'   or \code{"gcta"}. Ignored when \code{R} is provided directly.
#' @param ... Additional arguments passed to the underlying QC method
#'   (\code{\link{dentistSingleWindow}} or \code{\link{slalom}}).
#'
#' @return A data frame with at least a logical \code{outlier} column indicating
#'   which variants are identified as outliers. The remaining columns depend on
#'   the method used.
#'
#' @seealso \code{\link{dentistSingleWindow}}, \code{\link{slalom}},
#'   \code{\link{summaryStatsQc}}
#' @importFrom dplyr mutate row_number filter pull
#' @export
ldMismatchQc <- function(zScore, R = NULL, X = NULL, nSample = NULL,
                         method = c("slalom", "dentist"),
                         ldMethod = "sample", ...) {
  method <- match.arg(method)
  if (method == "dentist") {
    qcResults <- dentistSingleWindow(zScore, R = R, X = X, nSample = nSample,
                                     ldMethod = ldMethod, ...)
    return(qcResults)
  } else {
    qcResults <- slalom(zScore, R = R, X = X, ldMethod = ldMethod, ...)
    # Standardize output: slalom uses "outliers", rename to "outlier" for consistency
    result <- qcResults$data
    if ("outliers" %in% colnames(result) && !"outlier" %in% colnames(result)) {
      colnames(result)[colnames(result) == "outliers"] <- "outlier"
    }
    return(result)
  }
}

.resolveZMismatchQc <- function(zMismatchQc) {
  if (is.null(zMismatchQc)) return("none")
  match.arg(zMismatchQc, c("none", "slalom", "dentist"))
}

#' Kriging-style LD-consistency outlier QC
#'
#' Flags variants whose observed z-score is inconsistent with the value
#' predicted from its LD neighbours. For \code{z ~ N(0, R)} the leave-one-out
#' conditional distribution of \code{z_i} given the rest has mean
#' \code{-(1/Omega_ii) * Omega_{i,-i} z_{-i}} and variance \code{1/Omega_ii},
#' where \code{Omega = R^{-1}}. The standardized residual is ~\code{N(0,1)} when
#' the z-scores and LD are mutually consistent, so a large residual marks an
#' allele-flip / LD-mismatch outlier. RSS-only helper, opt-in via
#' \code{alleleFlipKriging}; never wired into \code{alleleQc()} /
#' \code{matchRefPanel()}.
#'
#' @param zScore Numeric vector of harmonized z-scores.
#' @param R Square LD correlation matrix aligned to \code{zScore}.
#' @param variantIds Optional variant IDs for the diagnostics table.
#' @param pThreshold Two-sided p-value cutoff for flagging an outlier
#'   (default \code{5e-8}).
#' @param ridge Small diagonal added to \code{R} before inversion for numerical
#'   stability (default \code{1e-3}).
#' @return A list with \code{outlier} (logical vector) and \code{diagnostics}
#'   (data frame of per-variant predicted z, residual, statistic, p-value, and
#'   outlier flag).
#' @importFrom stats pnorm
#' @export
krigingOutlierQc <- function(zScore, R, variantIds = NULL,
                             pThreshold = 5e-8, ridge = 1e-3) {
  zScore <- as.numeric(zScore)
  m <- length(zScore)
  if (is.null(R) || !is.matrix(R) || nrow(R) != m || ncol(R) != m) {
    stop("krigingOutlierQc requires a square LD matrix aligned to zScore.")
  }
  if (is.null(variantIds)) variantIds <- rownames(R)
  # Regularize so the precision matrix is well-defined for collinear panels.
  Omega <- solve(R + diag(ridge, m))
  d <- diag(Omega)
  omegaZ <- as.numeric(Omega %*% zScore)
  condMean <- -(omegaZ - d * zScore) / d
  condVar <- 1 / d
  residual <- zScore - condMean
  statistic <- residual / sqrt(condVar)
  pValue <- 2 * pnorm(-abs(statistic))
  outlier <- !is.na(pValue) & pValue < pThreshold
  list(
    outlier = outlier,
    diagnostics = data.frame(
      variant_id = if (is.null(variantIds)) seq_len(m) else variantIds,
      z = zScore, predicted = condMean, residual = residual,
      statistic = statistic, p_value = pValue, outlier = outlier,
      stringsAsFactors = FALSE
    )
  )
}

#' Perform Quality Control on Summary Statistics
#'
#' This function performs quality control on the processed summary statistics
#' using the specified method. It wraps \code{\link{ldMismatchQc}} and handles
#' subsetting of the summary statistics and LD matrix.
#'
#' @param sumstats A data frame containing the processed summary statistics.
#' @param ldData An \code{LdData} S4 object or a legacy list containing combined LD variants data,
#'   as generated by \code{loadLdMatrix}.
#' @param n Sample size for the LD reference panel (used by dentist method).
#' @param method The quality control method to use. Options are \code{"slalom"}
#'   or \code{"dentist"} (default: \code{"slalom"}).
#' @param rssInput Optional loaded RSS input, either one \code{loadRssData()}
#'   result or a named list of them. Supplying this selects the additional
#'   combined RSS/ColocBoost QC workflow. A single RSS record is detected by
#'   structure, not by the name \code{sumstats}, so a multi-study list may safely
#'   include a study named \code{"sumstats"}.
#' @param zMismatchQc The z-score / LD-mismatch QC selector for the combined
#'   workflow. One of \code{"none"} (default; basic allele harmonization only),
#'   \code{"slalom"}, or \code{"dentist"}. \code{NULL} resolves to \code{"none"}.
#'   (Hard rename of the former \code{qcMethod}; no alias.)
#' @param alleleFlipKriging Logical; opt-in kriging LD-consistency prefilter
#'   (\code{\link{krigingOutlierQc}}) run before the heavier QC, or standalone
#'   when \code{zMismatchQc = "none"}. Default \code{FALSE}.
#' @param keepIndel,skipRegion,pipCutoffToSkip,impute,imputeOpts,study,varY,returnOnSkip,R_finite,R_mismatch
#'   Additional controls for the combined RSS/ColocBoost QC workflow. They are
#'   ignored by the historical LD-mismatch-only call unless \code{rssInput} or
#'   combined-QC options are supplied.
#'
#' @return A \code{QcResult} S4 object for the historical LD-mismatch-only
#'   call (use \code{getRssInput()$sumstats}, \code{getCorrelation(getLdData())},
#'   and \code{getOutlierNumber()} to recover the harmonized sumstats, post-QC
#'   LD matrix, and outlier count). When \code{rssInput} or combined-QC
#'   controls are supplied, returns either a single \code{QcResult} (for one
#'   RSS record) or a named list of \code{QcResult} objects (for a list of
#'   RSS records).
#'
#' @details This function applies the specified quality control method to the
#'   processed summary statistics via \code{\link{ldMismatchQc}}, then subsets
#'   the summary statistics and LD matrix to keep only non-outlier variants.
#'
#'   As an additional workflow for ColocBoost/RSS pipelines, callers may supply
#'   \code{rssInput} or combined-QC controls. That path first runs
#'   \code{rssBasicQc()}, optional PIP screening, optional LD-mismatch QC
#'   through this same function, and optional RAISS imputation. The combined
#'   path normalizes one or many RSS records to the same loop internally; only
#'   true single-record input is unwrapped on return.
#'   \code{zMismatchQc = NULL} and \code{"none"} mean basic-only summary-stat
#'   preprocessing without SLALOM/DENTIST outlier QC.
#'
#'   When the combined path receives genotype-backed reference data
#'   (\code{X_ref}), basic harmonization avoids constructing an LD matrix. PIP
#'   screening uses the LD-independent single-effect summary-statistic model
#'   \code{susie_ser(coverage = NULL)}, and LD-mismatch QC
#'   computes only the filtered local correlation matrix required by
#'   SLALOM/DENTIST. RAISS imputation temporarily centers/scales
#'   genotype-backed \code{X_ref} before using the whole-region genotype/SVD
#'   path. This avoids LD-block partition artifacts while matching the LD scale
#'   used by \code{computeLd(X_ref)}. Final ColocBoost calls still keep the
#'   original \code{X_ref} as the reference input.
#'
#' @examples
#' # Perform SLALOM quality control (default)
#' qcResults <- summaryStatsQc(sumstats, ldData, method = "slalom")
#'
#' # Additional combined basic-only RSS QC.
#' qcResults <- summaryStatsQc(rssInput = rssInput, ldData = ldData,
#'                             zMismatchQc = "none")
#'
#' @importFrom dplyr mutate row_number filter pull
#' @importFrom susieR susie_ser
#' @export
summaryStatsQc <- function(sumstats, ldData, n = NULL,
                           method = c("slalom", "dentist"),
                           rssInput = NULL,
                           keepIndel = TRUE,
                           skipRegion = NULL,
                           pipCutoffToSkip = 0,
                           zMismatchQc = NULL,
                           alleleFlipKriging = FALSE,
                           impute = FALSE,
                           imputeOpts = list(rcond = 0.01, R2_threshold = 0.6,
                                             minimum_ld = 5, lamb = 0.01),
                           study = NULL,
                           varY = NULL,
                           returnOnSkip = c("null", "preprocess"),
                           R_finite = NULL,
                           R_mismatch = NULL) {
  if (missing(sumstats)) sumstats <- NULL
  returnOnSkip <- match.arg(returnOnSkip)
  if (is.null(rssInput) && is.data.frame(sumstats) && is.null(zMismatchQc) &&
      isFALSE(alleleFlipKriging) &&
      isFALSE(impute) && identical(pipCutoffToSkip, 0) && is.null(skipRegion)) {
    method <- match.arg(method)
    # When genotypes are available, compute R only for the needed variant subset
    if (is(ldData, "LdData") && hasGenotypes(ldData)) {
      X <- getGenotypes(ldData)
      vid <- getVariantIds(ldData)
      idx <- match(sumstats$variant_id, vid)
      X_sub <- X[, idx[!is.na(idx)], drop = FALSE]
      colnames(X_sub) <- sumstats$variant_id[!is.na(idx)]
      ldExtract <- computeLd(X_sub, method = "sample")
    } else {
      ldMat <- getCorrelation(ldData)
      ldExtract <- ldMat[sumstats$variant_id, sumstats$variant_id, drop = FALSE]
    }
    qcResults <- ldMismatchQc(zScore = sumstats$z, R = ldExtract,
                              nSample = n, method = method)
    keepIndex <- which(!qcResults$outlier)
    sumstatsQc <- sumstats[keepIndex, , drop = FALSE]
    ldMatQc <- ldExtract[sumstatsQc$variant_id, sumstatsQc$variant_id, drop = FALSE]
    outlierNumber <- nrow(sumstats) - nrow(sumstatsQc)
    nRef <- if (is(ldData, "LdData")) ldData@nRef else 0L
    return(QcResult(
      ldData = .qcLdDataFromMatrix(ldMatQc, sumstatsQc$variant_id,
                                   hasGenotype = FALSE, nRef = nRef),
      rssInput = list(sumstats = sumstatsQc, n = n,
                      varY = if (is.null(varY)) NA_real_ else varY),
      preprocess = list(),
      outlierNumber = outlierNumber,
      skipped = FALSE
    ))
  }

  zMismatchQc <- .resolveZMismatchQc(zMismatchQc)

  if (is.null(rssInput)) {
    if (is.null(sumstats)) stop("summaryStatsQc requires sumstats or rssInput.")
    rssInput <- if (is.data.frame(sumstats)) {
      list(sumstats = sumstats, n = n, varY = if (is.null(varY)) 1 else varY)
    } else {
      sumstats
    }
  }

  isRssRecord <- function(x) {
    is.list(x) && is.data.frame(x$sumstats)
  }
  isLdRecord <- function(x) {
    is(x, "LdData")
  }
  firstLdRecord <- function(x, studyName = NULL) {
    if (isLdRecord(x)) return(x)
    if (!is.null(studyName) && studyName %in% names(x)) return(x[[studyName]])
    if (is.list(x) && length(x) == 1) return(x[[1]])
    x
  }

  singleRssInput <- isRssRecord(rssInput)
  if (singleRssInput) {
    studies <- if (is.null(study)) "input" else study
    rssRecords <- stats::setNames(list(rssInput), studies)
    ldRecords <- stats::setNames(list(firstLdRecord(ldData, studies)), studies)
  } else {
    if (!is.list(rssInput) || length(rssInput) == 0) {
      stop("No summary-statistic studies supplied for QC.")
    }
    rssRecords <- rssInput
    studies <- names(rssRecords)
    if (is.null(studies)) studies <- rep("", length(rssRecords))
    emptyNames <- is.na(studies) | studies == ""
    if (any(emptyNames)) {
      studies[emptyNames] <- paste0("study", which(emptyNames))
      names(rssRecords) <- studies
    }
    if (!all(vapply(rssRecords, isRssRecord, logical(1)))) {
      stop("rssInput must be one RSS record or a list of RSS records with a sumstats data frame.")
    }

    if (isLdRecord(ldData)) {
      ldRecords <- stats::setNames(rep(list(ldData), length(studies)), studies)
    } else if (is.list(ldData) && length(ldData) == 1) {
      ldRecords <- stats::setNames(rep(list(ldData[[1]]), length(studies)), studies)
    } else if (is.list(ldData) && all(studies %in% names(ldData))) {
      ldRecords <- ldData[studies]
    } else if (is.list(ldData) && length(ldData) == length(studies)) {
      ldRecords <- ldData
      names(ldRecords) <- studies
    } else {
      stop("ldData must be one LD object or a list matching rssInput studies.")
    }
  }

  if (length(pipCutoffToSkip) == 1 && is.null(names(pipCutoffToSkip))) {
    cutoffs <- stats::setNames(rep(pipCutoffToSkip, length(studies)), studies)
  } else if (!is.null(names(pipCutoffToSkip))) {
    missing <- setdiff(studies, names(pipCutoffToSkip))
    if (length(missing) > 0) {
      pipCutoffToSkip <- c(pipCutoffToSkip, stats::setNames(rep(0, length(missing)), missing))
    }
    cutoffs <- pipCutoffToSkip[studies]
  } else if (length(pipCutoffToSkip) == length(studies)) {
    cutoffs <- stats::setNames(pipCutoffToSkip, studies)
  } else {
    stop("pipCutoffToSkip must be a scalar, named vector, or match the number of studies.")
  }

  out <- list()
  for (studyName in studies) {
    result <- .summaryStatsQcSingleStudy(
      rssRecords[[studyName]], ldRecords[[studyName]],
      keepIndel = keepIndel,
      skipRegion = skipRegion,
      pipCutoffToSkip = cutoffs[[studyName]],
      zMismatchQc = zMismatchQc,
      alleleFlipKriging = alleleFlipKriging,
      impute = impute,
      imputeOpts = imputeOpts,
      study = studyName,
      returnOnSkip = returnOnSkip,
      R_finite = R_finite,
      R_mismatch = R_mismatch
    )
    if (!is.null(result)) out[[studyName]] <- result
  }
  if (singleRssInput) out[[studies]] else out
}

.inferSingleLdBlockMetadata <- function(refPanel) {
  nVariants <- nrow(refPanel)
  data.frame(
    block_id = 1L,
    chrom = as.character(refPanel$chrom[1]),
    block_start = suppressWarnings(min(refPanel$pos, na.rm = TRUE)),
    block_end = suppressWarnings(max(refPanel$pos, na.rm = TRUE)),
    size = nVariants,
    start_idx = 1L,
    end_idx = nVariants,
    stringsAsFactors = FALSE
  )
}

.normalizeLdDataForQc <- function(ldData) {
  if (is.null(ldData)) return(NULL)
  if (!is(ldData, "LdData")) {
    stop("ldData must be an LdData object")
  }
  ldData
}

# Wrap a QC-stage LD payload (either a correlation matrix subset by variant_id,
# or a genotype matrix with colnames = variant_id) into an LdData. Used so the
# QcResult always carries an LdData rather than a bare matrix.
.qcLdDataFromMatrix <- function(mat, variants, hasGenotype, nRef = 0L) {
  if (is.null(mat) || length(variants) == 0L) return(NULL)
  parsed <- tryCatch(parseVariantId(variants), error = function(e) NULL)
  if (is.null(parsed)) return(NULL)
  parsed$variant_id <- variants
  parsed$chrom <- as.character(parsed$chrom)
  variantsGr <- .refPanelToGranges(parsed)
  bm <- .inferSingleLdBlockMetadata(parsed)
  if (hasGenotype) {
    LdData(
      correlation = NULL,
      genotypeHandle = mat,
      variants = variantsGr,
      blockMetadata = bm,
      nRef = as.integer(nRef)
    )
  } else {
    LdData(
      correlation = mat,
      variants = variantsGr,
      blockMetadata = bm,
      nRef = as.integer(nRef)
    )
  }
}

.summaryStatsQcSingleStudy <- function(rssInput, ldData, keepIndel, skipRegion,
                                       pipCutoffToSkip, zMismatchQc, impute,
                                       imputeOpts, study, returnOnSkip,
                                       alleleFlipKriging = FALSE,
                                       R_finite = NULL, R_mismatch = NULL) {
  if (is.null(rssInput) || is.null(ldData)) return(NULL)
  message("QC track: starting basic allele harmonization for summary-stat study ", study, ".")
  message("QC track: basic summary-stat QC requires sumstat$variant and ldData variant IDs ",
          "for study ", study, ".")
  ldDataForQc <- .normalizeLdDataForQc(ldData)
  hasGenotype <- hasGenotypes(ldDataForQc)
  refPanel <- getRefPanel(ldDataForQc)
  X_ref <- if (hasGenotype) getGenotypes(ldDataForQc) else NULL
  # getGenotypes() preserves the source variant ID convention (often
  # underscore-separated from PLINK), but sumstats$variant_id is colon-
  # separated canonical form. Canonicalize so downstream matching works.
  if (!is.null(X_ref)) {
    canonicalIds <- getVariantIds(ldDataForQc)
    if (length(canonicalIds) == ncol(X_ref)) colnames(X_ref) <- canonicalIds
  }
  nRefForQc <- ldDataForQc@nRef
  skippedResult <- function(sumstats, ldMat, reason) {
    if (!identical(returnOnSkip, "preprocess")) return(NULL)
    ld <- .qcLdDataFromMatrix(ldMat, sumstats$variant_id, hasGenotype, nRefForQc)
    QcResult(
      ldData = ld,
      rssInput = list(sumstats = sumstats, n = rssInput$n, varY = rssInput$varY),
      preprocess = list(sumstats = sumstats, ldData = ld),
      outlierNumber = 0L,
      skipped = TRUE,
      skipReason = reason
    )
  }
  basic <- rssBasicQc(rssInput$sumstats, ldDataForQc,
                      skipRegion = skipRegion, keepIndel = keepIndel,
                      returnLdMat = !hasGenotype)
  sumstats <- getRssInput(basic)$sumstats
  basicLd <- getLdData(basic)
  R_mat <- if (is.null(basicLd)) NULL else getCorrelation(basicLd)
  n <- rssInput$n
  varY <- rssInput$varY
  referenceForVariants <- function(variants) {
    if (hasGenotype) {
      refNames <- colnames(X_ref)
      refIdx <- match(variants, refNames)
      if (anyNA(refIdx)) {
        refIdx <- match(stripChrPrefix(stripBuildSuffix(variants)),
                        stripChrPrefix(stripBuildSuffix(refNames)))
      }
      if (anyNA(refIdx)) {
        missingVariants <- variants[is.na(refIdx)]
        stop("Genotype reference is missing ", length(missingVariants),
             " post-QC variant(s): ", paste(utils::head(missingVariants, 3), collapse = ", "))
      }
      X_subset <- X_ref[, refIdx, drop = FALSE]
      colnames(X_subset) <- variants
      return(X_subset)
    }
    if (is.null(R_mat)) return(NULL)
    R_mat[variants, variants, drop = FALSE]
  }
  ldDataWithLocalR <- function(currentSumstats) {
    if (!hasGenotype) return(ldDataForQc)
    variants <- currentSumstats$variant_id
    X_local <- referenceForVariants(variants)
    R_local <- computeLd(X_local, method = "sample")
    rownames(R_local) <- colnames(R_local) <- variants
    refIdx <- match(variants, refPanel$variant_id)
    if (anyNA(refIdx)) {
      refPanelSub <- parseVariantId(variants)
      refPanelSub$variant_id <- variants
    } else {
      refPanelSub <- refPanel[refIdx, , drop = FALSE]
    }
    variantsGr <- .refPanelToGranges(refPanelSub)
    R_mat <<- R_local
    LdData(
      correlation = R_local,
      variants = variantsGr,
      blockMetadata = .inferSingleLdBlockMetadata(refPanelSub),
      nRef = ldDataForQc@nRef
    )
  }
  message("QC track: basic harmonization retained ", nrow(sumstats),
          " variants for summary-stat study ", study, ".")
  if (nrow(sumstats) < 2) {
    return(skippedResult(sumstats, referenceForVariants(sumstats$variant_id),
                         "fewer than two variants remain after basic QC"))
  }

  preprocess <- list(sumstats = sumstats, ldMat = R_mat)
  if (!is.null(pipCutoffToSkip) && pipCutoffToSkip != 0) {
    cutoff <- pipCutoffToSkip
    if (cutoff < 0) cutoff <- 3 / nrow(sumstats)
    message("QC track: running LD-independent single-effect initial screen for summary-stat study ",
            study, ".")
    pip <- susie_ser(z = sumstats$z, n = n, coverage = NULL)$pip
    if (!any(pip > cutoff)) {
      message("Skipping follow-up analysis: No signals above PIP threshold ", cutoff)
      message("QC track: skipping summary-stat study ", study,
              ". No signals above PIP threshold ", cutoff, ".")
      return(skippedResult(sumstats, referenceForVariants(sumstats$variant_id),
                           "no signals above PIP threshold"))
    }
    message("Follow-up on region: signals above PIP threshold ", cutoff, " detected.")
  }

  outlierNumber <- 0L
  # Optional kriging LD-consistency prefilter (opt-in). Runs before the heavier
  # SLALOM/DENTIST QC, or standalone when zMismatchQc == "none".
  if (isTRUE(alleleFlipKriging) && nrow(sumstats) >= 2) {
    message("QC track: running kriging LD-consistency prefilter for summary-stat study ", study, ".")
    krLd <- ldDataWithLocalR(sumstats)
    rKr <- getCorrelation(krLd)
    rKr <- rKr[sumstats$variant_id, sumstats$variant_id, drop = FALSE]
    kr <- krigingOutlierQc(sumstats$z, rKr, variantIds = sumstats$variant_id)
    nKr <- sum(kr$outlier)
    if (nKr > 0) {
      sumstats <- sumstats[!kr$outlier, , drop = FALSE]
      if (!hasGenotype) R_mat <- R_mat[sumstats$variant_id, sumstats$variant_id, drop = FALSE]
      outlierNumber <- outlierNumber + nKr
    }
    message("QC track: kriging prefilter removed ", nKr,
            " LD-inconsistent variant(s) for summary-stat study ", study, ".")
  }
  if (!is.null(zMismatchQc) && !identical(zMismatchQc, "none")) {
    message("QC track: running ", zMismatchQc, " z-score/LD-mismatch QC for summary-stat study ", study, ".")
    qc <- summaryStatsQc(sumstats = sumstats, ldData = ldDataWithLocalR(sumstats),
                         n = n, method = zMismatchQc)
    qcRss <- getRssInput(qc)
    sumstats <- qcRss$sumstats
    qcLd <- getLdData(qc)
    R_mat <- if (is.null(qcLd)) NULL else getCorrelation(qcLd)
    ldMismatchOutliers <- getOutlierNumber(qc)
    outlierNumber <- outlierNumber + ldMismatchOutliers
    message("QC track: removed ", ldMismatchOutliers,
            " LD-mismatch outlier(s) for summary-stat study ", study, ".")
  }
  if (isTRUE(impute)) {
    message("QC track: running imputation for summary-stat study ", study, ".")
    imputed <- if (hasGenotype) {
      X_ref_scaled <- scale(X_ref)
      X_ref_scaled[is.na(X_ref_scaled)] <- 0
      colnames(X_ref_scaled) <- colnames(X_ref)
      raiss(refPanel, sumstats,
            genotypeMatrix = X_ref_scaled,
            svdTol = if (is.null(imputeOpts$svd_tol)) 1e-12 else imputeOpts$svd_tol,
            r2Threshold = imputeOpts$R2_threshold,
            minimumLd = imputeOpts$minimum_ld,
            lamb = imputeOpts$lamb)
    } else {
      raiss(refPanel, sumstats, partitionLdMatrix(ldDataForQc),
            rcond = imputeOpts$rcond,
            r2Threshold = imputeOpts$R2_threshold,
            minimumLd = imputeOpts$minimum_ld,
            lamb = imputeOpts$lamb)
    }
    sumstats <- imputed$result_filter
    if (!is.null(imputed$LD_mat)) R_mat <- imputed$LD_mat
  }
  finalVars <- sumstats$variant_id
  finalLdMat <- if (hasGenotype) referenceForVariants(finalVars) else R_mat
  preprocessSumstats <- preprocess$sumstats
  preprocessLdMat <- preprocess$ldMat
  preprocessLdVars <- if (hasGenotype) preprocessSumstats$variant_id else rownames(preprocessLdMat)
  QcResult(
    ldData = .qcLdDataFromMatrix(finalLdMat, finalVars, hasGenotype, nRefForQc),
    rssInput = list(sumstats = sumstats, n = n, varY = varY),
    preprocess = list(
      sumstats = preprocessSumstats,
      ldData = .qcLdDataFromMatrix(preprocessLdMat, preprocessLdVars, hasGenotype, nRefForQc)
    ),
    outlierNumber = outlierNumber,
    skipped = FALSE
  )
}
